aebs_trevor:
  target: dev
  outputs:
    dev:
      type: snowflake
      
      # authentification
      user: #<username>
      password: #<password>
      account: #<account>
      
      # parameters
      database: #<database>
      warehouse: #<warehouse>
      schema: #<schema>
      threads: 4
      client_session_keep_alive: False
      query_tag: put_tag_here
      
